name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.PROD_DEPLOY_KEY }}

    - name: Deploy to production server
      run: |
        ssh u1779561@37.140.192.91 "
        source ./.bashrc
        cd /www/jahankeshde.com/ &&

        # Pull the latest code
        git pull origin master &&

        # Check if composer dependencies changed, then run composer install
        if git diff --name-only HEAD^ HEAD | grep -qE 'composer.json|composer.lock'; then
          echo 'Composer dependencies changed, running composer install...'
          composer install --no-dev --optimize-autoloader
        else
          echo 'Composer dependencies have not changed, skipping composer install.'
        fi &&

        # Check if npm dependencies changed, then run npm install
        if git diff --name-only HEAD^ HEAD | grep -qE 'package.json|package-lock.json'; then
          echo 'npm dependencies changed, running npm install...'
          npm install
        else
          echo 'npm dependencies have not changed, skipping npm install.'
        fi &&

        # Build the frontend assets
        npm run build &&

        # Run Laravel migrations
        php artisan migrate --force &&

        # Clear and cache configurations
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan view:cache
        "
